using System;

namespace Toolkit {
    public static partial class ColorTable {
        public static class RichTextTags {
            #region Consts

            public const string MAROON = "<color=#800000>";
            public const string DARKRED = "<color=#8B0000>";
            public const string BROWN = "<color=#A52A2A>";
            public const string FIREBRICK = "<color=#B22222>";
            public const string CRIMSON = "<color=#DC143C>";
            public const string RED = "<color=#FF0000>";
            public const string TOMATO = "<color=#FF6347>";
            public const string CORAL = "<color=#FF7F50>";
            public const string INDIANRED = "<color=#CD5C5C>";
            public const string LIGHTCORAL = "<color=#F08080>";
            public const string DARKSALMON = "<color=#E9967A>";
            public const string SALMON = "<color=#FA8072>";
            public const string LIGHTSALMON = "<color=#FFA07A>";
            public const string ORANGERED = "<color=#FF4500>";
            public const string DARKORANGE = "<color=#FF8C00>";
            public const string ORANGE = "<color=#FFA500>";
            public const string GOLD = "<color=#FFD700>";
            public const string DARKGOLDENROD = "<color=#B8860B>";
            public const string GOLDENROD = "<color=#DAA520>";
            public const string PALEGOLDENROD = "<color=#EEE8AA>";
            public const string DARKKHAKI = "<color=#BDB76B>";
            public const string KHAKI = "<color=#F0E68C>";
            public const string OLIVE = "<color=#808000>";
            public const string YELLOW = "<color=#FFFF00>";
            public const string YELLOWGREEN = "<color=#9ACD32>";
            public const string DARKOLIVEGREEN = "<color=#556B2F>";
            public const string OLIVEDRAB = "<color=#6B8E23>";
            public const string LAWNGREEN = "<color=#7CFC00>";
            public const string CHARTREUSE = "<color=#7FFF00>";
            public const string GREENYELLOW = "<color=#ADFF2F>";
            public const string DARKGREEN = "<color=#006400>";
            public const string GREEN = "<color=#008000>";
            public const string FORESTGREEN = "<color=#228B22>";
            public const string LIME = "<color=#00FF00>";
            public const string LIMEGREEN = "<color=#32CD32>";
            public const string LIGHTGREEN = "<color=#90EE90>";
            public const string PALEGREEN = "<color=#98FB98>";
            public const string DARKSEAGREEN = "<color=#8FBC8F>";
            public const string MEDIUMSPRINGGREEN = "<color=#00FA9A>";
            public const string SPRINGGREEN = "<color=#00FF7F>";
            public const string SEAGREEN = "<color=#2E8B57>";
            public const string MEDIUMAQUAMARINE = "<color=#66CDAA>";
            public const string MEDIUMSEAGREEN = "<color=#3CB371>";
            public const string LIGHTSEAGREEN = "<color=#20B2AA>";
            public const string DARKSLATEGRAY = "<color=#2F4F4F>";
            public const string TEAL = "<color=#008080>";
            public const string DARKCYAN = "<color=#008B8B>";
            public const string AQUA = "<color=#00FFFF>";
            public const string CYAN = "<color=#00FFFF>";
            public const string LIGHTCYAN = "<color=#E0FFFF>";
            public const string DARKTURQUOISE = "<color=#00CED1>";
            public const string TURQUOISE = "<color=#40E0D0>";
            public const string MEDIUMTURQUOISE = "<color=#48D1CC>";
            public const string PALETURQUOISE = "<color=#AFEEEE>";
            public const string AQUAMARINE = "<color=#7FFFD4>";
            public const string POWDERBLUE = "<color=#B0E0E6>";
            public const string CADETBLUE = "<color=#5F9EA0>";
            public const string STEELBLUE = "<color=#4682B4>";
            public const string CORNFLOWERBLUE = "<color=#6495ED>";
            public const string DEEPSKYBLUE = "<color=#00BFFF>";
            public const string DODGERBLUE = "<color=#1E90FF>";
            public const string LIGHTBLUE = "<color=#ADD8E6>";
            public const string SKYBLUE = "<color=#87CEEB>";
            public const string LIGHTSKYBLUE = "<color=#87CEFA>";
            public const string MIDNIGHTBLUE = "<color=#191970>";
            public const string NAVY = "<color=#000080>";
            public const string DARKBLUE = "<color=#00008B>";
            public const string MEDIUMBLUE = "<color=#0000CD>";
            public const string BLUE = "<color=#0000FF>";
            public const string ROYALBLUE = "<color=#4169E1>";
            public const string BLUEVIOLET = "<color=#8A2BE2>";
            public const string INDIGO = "<color=#4B0082>";
            public const string DARKSLATEBLUE = "<color=#483D8B>";
            public const string SLATEBLUE = "<color=#6A5ACD>";
            public const string MEDIUMSLATEBLUE = "<color=#7B68EE>";
            public const string MEDIUMPURPLE = "<color=#9370DB>";
            public const string DARKMAGENTA = "<color=#8B008B>";
            public const string DARKVIOLET = "<color=#9400D3>";
            public const string DARKORCHID = "<color=#9932CC>";
            public const string MEDIUMORCHID = "<color=#BA55D3>";
            public const string PURPLE = "<color=#800080>";
            public const string THISTLE = "<color=#D8BFD8>";
            public const string PLUM = "<color=#DDA0DD>";
            public const string VIOLET = "<color=#EE82EE>";
            public const string MAGENTA = "<color=#FF00FF>";
            public const string FUCHSIA = "<color=#FF00FF>";
            public const string ORCHID = "<color=#DA70D6>";
            public const string MEDIUMVIOLETRED = "<color=#C71585>";
            public const string PALEVIOLETRED = "<color=#DB7093>";
            public const string DEEPPINK = "<color=#FF1493>";
            public const string HOTPINK = "<color=#FF69B4>";
            public const string LIGHTPINK = "<color=#FFB6C1>";
            public const string PINK = "<color=#FFC0CB>";
            public const string ANTIQUEWHITE = "<color=#FAEBD7>";
            public const string BEIGE = "<color=#F5F5DC>";
            public const string BISQUE = "<color=#FFE4C4>";
            public const string BLANCHEDALMOND = "<color=#FFEBCD>";
            public const string WHEAT = "<color=#F5DEB3>";
            public const string CORNSILK = "<color=#FFF8DC>";
            public const string LEMONCHIFFON = "<color=#FFFACD>";
            public const string LIGHTGOLDENRODYELLOW = "<color=#FAFAD2>";
            public const string LIGHTYELLOW = "<color=#FFFFE0>";
            public const string SADDLEBROWN = "<color=#8B4513>";
            public const string SIENNA = "<color=#A0522D>";
            public const string CHOCOLATE = "<color=#D2691E>";
            public const string PERU = "<color=#CD853F>";
            public const string SANDYBROWN = "<color=#F4A460>";
            public const string BURLYWOOD = "<color=#DEB887>";
            public const string TAN = "<color=#D2B48C>";
            public const string ROSYBROWN = "<color=#BC8F8F>";
            public const string MOCCASIN = "<color=#FFE4B5>";
            public const string NAVAJOWHITE = "<color=#FFDEAD>";
            public const string PEACHPUFF = "<color=#FFDAB9>";
            public const string MISTYROSE = "<color=#FFE4E1>";
            public const string LAVENDERBLUSH = "<color=#FFF0F5>";
            public const string LINEN = "<color=#FAF0E6>";
            public const string OLDLACE = "<color=#FDF5E6>";
            public const string PAPAYAWHIP = "<color=#FFEFD5>";
            public const string SEASHELL = "<color=#FFF5EE>";
            public const string MINTCREAM = "<color=#F5FFFA>";
            public const string SLATEGRAY = "<color=#708090>";
            public const string LIGHTSLATEGRAY = "<color=#778899>";
            public const string LIGHTSTEELBLUE = "<color=#B0C4DE>";
            public const string LAVENDER = "<color=#E6E6FA>";
            public const string FLORALWHITE = "<color=#FFFAF0>";
            public const string ALICEBLUE = "<color=#F0F8FF>";
            public const string GHOSTWHITE = "<color=#F8F8FF>";
            public const string HONEYDEW = "<color=#F0FFF0>";
            public const string IVORY = "<color=#FFFFF0>";
            public const string AZURE = "<color=#F0FFFF>";
            public const string SNOW = "<color=#FFFAFA>";
            public const string BLACK = "<color=#000000>";
            public const string DIMGRAY = "<color=#696969>";
            public const string DIMGREY = "<color=#696969>";
            public const string GRAY = "<color=#808080>";
            public const string GREY = "<color=#808080>";
            public const string DARKGRAY = "<color=#A9A9A9>";
            public const string DARKGREY = "<color=#A9A9A9>";
            public const string SILVER = "<color=#C0C0C0>";
            public const string LIGHTGRAY = "<color=#D3D3D3>";
            public const string LIGHTGREY = "<color=#D3D3D3>";
            public const string GAINSBORO = "<color=#DCDCDC>";
            public const string WHITESMOKE = "<color=#F5F5F5>";
            public const string WHITE = "<color=#FFFFFF>";

            #endregion

            #region Formatting

            public static string Format(string text, ColorTableType type) {
                return $"{GetTag(type)}{text}</color>";
            }

            #endregion

            #region Get Tag Utility

            public static string GetTag(ColorTableType type) {
                switch (type) {
                    case ColorTableType.Maroon: return MAROON;
                    case ColorTableType.DarkRed: return DARKRED;
                    case ColorTableType.Brown: return BROWN;
                    case ColorTableType.Firebrick: return FIREBRICK;
                    case ColorTableType.Crimson: return CRIMSON;
                    case ColorTableType.Red: return RED;
                    case ColorTableType.Tomato: return TOMATO;
                    case ColorTableType.Coral: return CORAL;
                    case ColorTableType.IndianRed: return INDIANRED;
                    case ColorTableType.LightCoral: return LIGHTCORAL;
                    case ColorTableType.DarkSalmon: return DARKSALMON;
                    case ColorTableType.Salmon: return SALMON;
                    case ColorTableType.LightSalmon: return LIGHTSALMON;
                    case ColorTableType.OrangeRed: return ORANGERED;
                    case ColorTableType.DarkOrange: return DARKORANGE;
                    case ColorTableType.Orange: return ORANGE;
                    case ColorTableType.Gold: return GOLD;
                    case ColorTableType.DarkGoldenRod: return DARKGOLDENROD;
                    case ColorTableType.GoldenRod: return GOLDENROD;
                    case ColorTableType.PaleGoldenRod: return PALEGOLDENROD;
                    case ColorTableType.DarkKhaki: return DARKKHAKI;
                    case ColorTableType.Khaki: return KHAKI;
                    case ColorTableType.Olive: return OLIVE;
                    case ColorTableType.Yellow: return YELLOW;
                    case ColorTableType.YellowGreen: return YELLOWGREEN;
                    case ColorTableType.DarkOliveGreen: return DARKOLIVEGREEN;
                    case ColorTableType.OliveDrab: return OLIVEDRAB;
                    case ColorTableType.LawnGreen: return LAWNGREEN;
                    case ColorTableType.ChartReuse: return CHARTREUSE;
                    case ColorTableType.GreenYellow: return GREENYELLOW;
                    case ColorTableType.DarkGreen: return DARKGREEN;
                    case ColorTableType.Green: return GREEN;
                    case ColorTableType.ForestGreen: return FORESTGREEN;
                    case ColorTableType.Lime: return LIME;
                    case ColorTableType.LimeGreen: return LIMEGREEN;
                    case ColorTableType.LightGreen: return LIGHTGREEN;
                    case ColorTableType.PaleGreen: return PALEGREEN;
                    case ColorTableType.DarkSeaGreen: return DARKSEAGREEN;
                    case ColorTableType.MediumSpringGreen: return MEDIUMSPRINGGREEN;
                    case ColorTableType.SpringGreen: return SPRINGGREEN;
                    case ColorTableType.SeaGreen: return SEAGREEN;
                    case ColorTableType.MediumAquaMarine: return MEDIUMAQUAMARINE;
                    case ColorTableType.MediumSeaGreen: return MEDIUMSEAGREEN;
                    case ColorTableType.LightSeaGreen: return LIGHTSEAGREEN;
                    case ColorTableType.DarkSlateGray: return DARKSLATEGRAY;
                    case ColorTableType.Teal: return TEAL;
                    case ColorTableType.DarkCyan: return DARKCYAN;
                    case ColorTableType.Aqua: return AQUA;
                    case ColorTableType.Cyan: return CYAN;
                    case ColorTableType.LightCyan: return LIGHTCYAN;
                    case ColorTableType.DarkTurquoise: return DARKTURQUOISE;
                    case ColorTableType.Turquoise: return TURQUOISE;
                    case ColorTableType.MediumTurquoise: return MEDIUMTURQUOISE;
                    case ColorTableType.PaleTurquoise: return PALETURQUOISE;
                    case ColorTableType.AquaMarine: return AQUAMARINE;
                    case ColorTableType.PowderBlue: return POWDERBLUE;
                    case ColorTableType.CadetBlue: return CADETBLUE;
                    case ColorTableType.SteelBlue: return STEELBLUE;
                    case ColorTableType.CornFlowerBlue: return CORNFLOWERBLUE;
                    case ColorTableType.DeepSkyBlue: return DEEPSKYBLUE;
                    case ColorTableType.DodgerBlue: return DODGERBLUE;
                    case ColorTableType.LightBlue: return LIGHTBLUE;
                    case ColorTableType.SkyBlue: return SKYBLUE;
                    case ColorTableType.LightSkyBlue: return LIGHTSKYBLUE;
                    case ColorTableType.MidnightBlue: return MIDNIGHTBLUE;
                    case ColorTableType.Navy: return NAVY;
                    case ColorTableType.DarkBlue: return DARKBLUE;
                    case ColorTableType.MediumBlue: return MEDIUMBLUE;
                    case ColorTableType.Blue: return BLUE;
                    case ColorTableType.RoyalBlue: return ROYALBLUE;
                    case ColorTableType.BlueViolet: return BLUEVIOLET;
                    case ColorTableType.Indigo: return INDIGO;
                    case ColorTableType.DarkSlateBlue: return DARKSLATEBLUE;
                    case ColorTableType.SlateBlue: return SLATEBLUE;
                    case ColorTableType.MediumSlateBlue: return MEDIUMSLATEBLUE;
                    case ColorTableType.MediumPurple: return MEDIUMPURPLE;
                    case ColorTableType.DarkMagenta: return DARKMAGENTA;
                    case ColorTableType.DarkViolet: return DARKVIOLET;
                    case ColorTableType.DarkOrchid: return DARKORCHID;
                    case ColorTableType.MediumOrchid: return MEDIUMORCHID;
                    case ColorTableType.Purple: return PURPLE;
                    case ColorTableType.Thistle: return THISTLE;
                    case ColorTableType.Plum: return PLUM;
                    case ColorTableType.Violet: return VIOLET;
                    case ColorTableType.Magenta: return MAGENTA;
                    case ColorTableType.Orchid: return ORCHID;
                    case ColorTableType.MediumVioletRed: return MEDIUMVIOLETRED;
                    case ColorTableType.PaleVioletRed: return PALEVIOLETRED;
                    case ColorTableType.DeepPink: return DEEPPINK;
                    case ColorTableType.HotPink: return HOTPINK;
                    case ColorTableType.LightPink: return LIGHTPINK;
                    case ColorTableType.Pink: return PINK;
                    case ColorTableType.AntiqueWhite: return ANTIQUEWHITE;
                    case ColorTableType.Beige: return BEIGE;
                    case ColorTableType.Bisque: return BISQUE;
                    case ColorTableType.BlanchedAlmond: return BLANCHEDALMOND;
                    case ColorTableType.Wheat: return WHEAT;
                    case ColorTableType.CornSilk: return CORNSILK;
                    case ColorTableType.LemonChiffon: return LEMONCHIFFON;
                    case ColorTableType.LightGoldenRodYellow: return LIGHTGOLDENRODYELLOW;
                    case ColorTableType.LightYellow: return LIGHTYELLOW;
                    case ColorTableType.SaddleBrown: return SADDLEBROWN;
                    case ColorTableType.Sienna: return SIENNA;
                    case ColorTableType.Chocolate: return CHOCOLATE;
                    case ColorTableType.Peru: return PERU;
                    case ColorTableType.SandyBrown: return SANDYBROWN;
                    case ColorTableType.BurlyWood: return BURLYWOOD;
                    case ColorTableType.Tan: return TAN;
                    case ColorTableType.RosyBrown: return ROSYBROWN;
                    case ColorTableType.Moccasin: return MOCCASIN;
                    case ColorTableType.NavajoWhite: return NAVAJOWHITE;
                    case ColorTableType.PeachPuff: return PEACHPUFF;
                    case ColorTableType.MistyRose: return MISTYROSE;
                    case ColorTableType.LavenderBlush: return LAVENDERBLUSH;
                    case ColorTableType.Linen: return LINEN;
                    case ColorTableType.OldLace: return OLDLACE;
                    case ColorTableType.PapayaWhip: return PAPAYAWHIP;
                    case ColorTableType.SeaShell: return SEASHELL;
                    case ColorTableType.MintCream: return MINTCREAM;
                    case ColorTableType.SlateGray: return SLATEGRAY;
                    case ColorTableType.LightSlateGray: return LIGHTSLATEGRAY;
                    case ColorTableType.LightSteelBlue: return LIGHTSTEELBLUE;
                    case ColorTableType.Lavender: return LAVENDER;
                    case ColorTableType.FloralWhite: return FLORALWHITE;
                    case ColorTableType.AliceBlue: return ALICEBLUE;
                    case ColorTableType.GhostWhite: return GHOSTWHITE;
                    case ColorTableType.Honeydew: return HONEYDEW;
                    case ColorTableType.Ivory: return IVORY;
                    case ColorTableType.Azure: return AZURE;
                    case ColorTableType.Snow: return SNOW;
                    case ColorTableType.Black: return BLACK;
                    case ColorTableType.DimGray: return DIMGRAY;
                    case ColorTableType.Gray: return GRAY;
                    case ColorTableType.DarkGray: return DARKGRAY;
                    case ColorTableType.Silver: return SILVER;
                    case ColorTableType.LightGray: return LIGHTGRAY;
                    case ColorTableType.Gainsboro: return GAINSBORO;
                    case ColorTableType.WhiteSmoke: return WHITESMOKE;
                    case ColorTableType.White: return WHITE;
                }
                return WHITE;
            }

            #endregion
        }
    }
}
